//! Compile-time embedded skill files, auto-generated by `build.rs`.

/// A file bundled within a skill directory, embedded at compile time.
pub(crate) struct BundledFile {
    /// Relative path within the skill directory.
    pub rel_path: &'static str,
    /// File content embedded at compile time.
    pub content: &'static str,
}

include!(concat!(env!("OUT_DIR"), "/bundled_skills.rs"));
