//! Build script — auto-discovers all files under `skills/` in the repo root
//! and generates `bundled_skills.rs` with compile-time `include_str!` entries.

use std::fmt::Write as _;
use std::path::Path;
use std::{env, fs};

fn main() {
    let skills_dir = Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join("..")
        .join("..")
        .join("skills");

    // Rerun if anything under skills/ changes.
    println!("cargo:rerun-if-changed={}", skills_dir.display());

    let out_dir = env::var("OUT_DIR").unwrap();
    let dest = Path::new(&out_dir).join("bundled_skills.rs");

    let mut code = String::from(
        "/// Auto-generated by build.rs — do not edit.\n\
         pub(crate) const BUNDLED_SKILLS: &[(&str, &[BundledFile])] = &[\n",
    );

    // Collect skill directories (sorted for deterministic output).
    let mut skill_dirs: Vec<_> = fs::read_dir(&skills_dir)
        .expect("cannot read skills/ directory")
        .filter_map(|e| e.ok())
        .filter(|e| e.path().is_dir())
        .collect();
    skill_dirs.sort_by_key(|e| e.file_name());

    for entry in &skill_dirs {
        let skill_name = entry.file_name();
        let skill_name = skill_name.to_str().unwrap();
        let skill_path = entry.path();

        // Only include directories that have a SKILL.md.
        if !skill_path.join("SKILL.md").exists() {
            continue;
        }

        // Collect all files recursively.
        let mut files = Vec::new();
        collect_files(&skill_path, &skill_path, &mut files);
        files.sort();

        writeln!(code, "    (\"{skill_name}\", &[").unwrap();
        for rel_path in &files {
            let abs_path = skills_dir.join(skill_name).join(rel_path);
            let abs_path = abs_path.canonicalize().unwrap();
            let abs_str = abs_path.display();
            writeln!(
                code,
                "        BundledFile {{ rel_path: \"{rel_path}\", content: include_str!(\"{abs_str}\") }},"
            )
            .unwrap();
        }
        writeln!(code, "    ]),").unwrap();
    }

    code.push_str("];\n");
    fs::write(&dest, code).unwrap();
}

/// Recursively collect relative file paths under `base`, skipping hidden files.
fn collect_files(base: &Path, dir: &Path, out: &mut Vec<String>) {
    let entries = match fs::read_dir(dir) {
        Ok(e) => e,
        Err(_) => return,
    };
    for entry in entries.flatten() {
        let path = entry.path();
        let name = entry.file_name();
        let name_str = name.to_str().unwrap_or("");
        // Skip hidden files/dirs (.DS_Store, .git, etc.).
        if name_str.starts_with('.') {
            continue;
        }
        if path.is_dir() {
            collect_files(base, &path, out);
        } else {
            let rel = path.strip_prefix(base).unwrap();
            out.push(rel.to_str().unwrap().to_string());
        }
    }
}
